CREATE TABLE country(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(50),
PRIMARY KEY (id)
);

INSERT INTO country(id,name) VALUES (1,'Algeria');
INSERT INTO country(id,name) VALUES (2,'Egypt');
INSERT INTO country(id,name) VALUES (3,'Libya');
INSERT INTO country(id,name) VALUES (4,'Morocco');
INSERT INTO country(id,name) VALUES (5,'Tunisia');
INSERT INTO country(id,name) VALUES (6,'Western Sahara');
INSERT INTO country(id,name) VALUES (7,'Angola');
INSERT INTO country(id,name) VALUES (8,'Benin');
INSERT INTO country(id,name) VALUES (9,'Botswana');
INSERT INTO country(id,name) VALUES (10,'Burkina Faso');
INSERT INTO country(id,name) VALUES (11,'Burundi');
INSERT INTO country(id,name) VALUES (12,'Cameroon');
INSERT INTO country(id,name) VALUES (13,'Cape Verde');
INSERT INTO country(id,name) VALUES (14,'Central African Republic');
INSERT INTO country(id,name) VALUES (15,'Chad');
INSERT INTO country(id,name) VALUES (16,'Comoros');
INSERT INTO country(id,name) VALUES (17,'Congo');
INSERT INTO country(id,name) VALUES (18,'Congo, The Democratic Republic of the');
INSERT INTO country(id,name) VALUES (19,'CÈte d''Ivoire');
INSERT INTO country(id,name) VALUES (20,'Djibouti');
INSERT INTO country(id,name) VALUES (21,'Equatorial Guinea');
INSERT INTO country(id,name) VALUES (22,'Eritrea');
INSERT INTO country(id,name) VALUES (23,'Ethiopia');
INSERT INTO country(id,name) VALUES (24,'Gabon');
INSERT INTO country(id,name) VALUES (25,'Gambia');
INSERT INTO country(id,name) VALUES (26,'Ghana');
INSERT INTO country(id,name) VALUES (27,'Guinea');
INSERT INTO country(id,name) VALUES (28,'Guinea-Bissau');
INSERT INTO country(id,name) VALUES (29,'Kenya');
INSERT INTO country(id,name) VALUES (30,'Lesotho');
INSERT INTO country(id,name) VALUES (31,'Liberia');
INSERT INTO country(id,name) VALUES (32,'Madagascar');
INSERT INTO country(id,name) VALUES (33,'Malawi');
INSERT INTO country(id,name) VALUES (34,'Mali');
INSERT INTO country(id,name) VALUES (35,'Mauritania');
INSERT INTO country(id,name) VALUES (36,'Mauritius');
INSERT INTO country(id,name) VALUES (37,'Mayotte');
INSERT INTO country(id,name) VALUES (38,'Mozambique');
INSERT INTO country(id,name) VALUES (39,'Namibia');
INSERT INTO country(id,name) VALUES (40,'Niger');
INSERT INTO country(id,name) VALUES (41,'Nigeria');
INSERT INTO country(id,name) VALUES (42,'R_union');
INSERT INTO country(id,name) VALUES (43,'Rwanda');
INSERT INTO country(id,name) VALUES (44,'Saint Helena, Ascension and Tristan da Cunha');
INSERT INTO country(id,name) VALUES (45,'Sao Tom_ and Principe');
INSERT INTO country(id,name) VALUES (46,'Senegal');
INSERT INTO country(id,name) VALUES (47,'Seychelles');
INSERT INTO country(id,name) VALUES (48,'Sierra Leone');
INSERT INTO country(id,name) VALUES (49,'Somalia');
INSERT INTO country(id,name) VALUES (50,'South Africa');
INSERT INTO country(id,name) VALUES (51,'South Sudan');
INSERT INTO country(id,name) VALUES (52,'Sudan');
INSERT INTO country(id,name) VALUES (53,'Swaziland');
INSERT INTO country(id,name) VALUES (54,'Tanzania, United Republic of');
INSERT INTO country(id,name) VALUES (55,'Togo');
INSERT INTO country(id,name) VALUES (56,'Uganda');
INSERT INTO country(id,name) VALUES (57,'Zambia');
INSERT INTO country(id,name) VALUES (58,'Zimbabwe');
INSERT INTO country(id,name) VALUES (59,'Antarctica');
INSERT INTO country(id,name) VALUES (60,'Bouvet Island');
INSERT INTO country(id,name) VALUES (61,'French Southern Territories');
INSERT INTO country(id,name) VALUES (62,'Heard Island and McDonald Islands');
INSERT INTO country(id,name) VALUES (63,'South Georgia and the South Sandwich Islands');
INSERT INTO country(id,name) VALUES (64,'China');
INSERT INTO country(id,name) VALUES (65,'Hong Kong');
INSERT INTO country(id,name) VALUES (66,'Japan');
INSERT INTO country(id,name) VALUES (67,'Korea, Democratic People''s Republic of');
INSERT INTO country(id,name) VALUES (68,'Korea, Republic of');
INSERT INTO country(id,name) VALUES (69,'Macao');
INSERT INTO country(id,name) VALUES (70,'Mongolia');
INSERT INTO country(id,name) VALUES (71,'Taiwan, Province of China');
INSERT INTO country(id,name) VALUES (72,'Belarus');
INSERT INTO country(id,name) VALUES (73,'Moldova');
INSERT INTO country(id,name) VALUES (74,'Russian Federation');
INSERT INTO country(id,name) VALUES (75,'Ukraine');
INSERT INTO country(id,name) VALUES (76,'Bangladesh');
INSERT INTO country(id,name) VALUES (77,'Bhutan');
INSERT INTO country(id,name) VALUES (78,'British Indian Ocean Territory');
INSERT INTO country(id,name) VALUES (79,'Brunei Darussalam');
INSERT INTO country(id,name) VALUES (80,'Cambodia');
INSERT INTO country(id,name) VALUES (81,'Disputed Territory');
INSERT INTO country(id,name) VALUES (82,'India');
INSERT INTO country(id,name) VALUES (83,'Indonesia');
INSERT INTO country(id,name) VALUES (84,'Lao People''s Democratic Republic');
INSERT INTO country(id,name) VALUES (85,'Malaysia');
INSERT INTO country(id,name) VALUES (86,'Maldives');
INSERT INTO country(id,name) VALUES (87,'Myanmar');
INSERT INTO country(id,name) VALUES (88,'Nepal');
INSERT INTO country(id,name) VALUES (89,'Philippines');
INSERT INTO country(id,name) VALUES (90,'Singapore');
INSERT INTO country(id,name) VALUES (91,'Sri Lanka');
INSERT INTO country(id,name) VALUES (92,'Thailand');
INSERT INTO country(id,name) VALUES (93,'Timor-Leste');
INSERT INTO country(id,name) VALUES (94,'Viet Nam');
INSERT INTO country(id,name) VALUES (95,'Afghanistan');
INSERT INTO country(id,name) VALUES (96,'Armenia');
INSERT INTO country(id,name) VALUES (97,'Azerbaijan');
INSERT INTO country(id,name) VALUES (98,'Bahrain');
INSERT INTO country(id,name) VALUES (99,'Cyprus');
INSERT INTO country(id,name) VALUES (100,'Georgia');
INSERT INTO country(id,name) VALUES (101,'Iran, Islamic Republic of');
INSERT INTO country(id,name) VALUES (102,'Iraq');
INSERT INTO country(id,name) VALUES (103,'Israel');
INSERT INTO country(id,name) VALUES (104,'Jordan');
INSERT INTO country(id,name) VALUES (105,'Kazakhstan');
INSERT INTO country(id,name) VALUES (106,'Kuwait');
INSERT INTO country(id,name) VALUES (107,'Kyrgyzstan');
INSERT INTO country(id,name) VALUES (108,'Lebanon');
INSERT INTO country(id,name) VALUES (109,'Oman');
INSERT INTO country(id,name) VALUES (110,'Pakistan');
INSERT INTO country(id,name) VALUES (111,'Palestinian Territory, Occupied');
INSERT INTO country(id,name) VALUES (112,'Qatar');
INSERT INTO country(id,name) VALUES (113,'Saudi Arabia');
INSERT INTO country(id,name) VALUES (114,'Syrian Arab Republic');
INSERT INTO country(id,name) VALUES (115,'Tajikistan');
INSERT INTO country(id,name) VALUES (116,'Turkey');
INSERT INTO country(id,name) VALUES (117,'Turkmenistan');
INSERT INTO country(id,name) VALUES (118,'United Arab Emirates');
INSERT INTO country(id,name) VALUES (119,'Uzbekistan');
INSERT INTO country(id,name) VALUES (120,'Yemen');
INSERT INTO country(id,name) VALUES (121,'Albania');
INSERT INTO country(id,name) VALUES (122,'Andorra');
INSERT INTO country(id,name) VALUES (123,'Austria');
INSERT INTO country(id,name) VALUES (124,'Belgium');
INSERT INTO country(id,name) VALUES (125,'Bosnia and Herzegovina');
INSERT INTO country(id,name) VALUES (126,'Bulgaria');
INSERT INTO country(id,name) VALUES (127,'Croatia');
INSERT INTO country(id,name) VALUES (128,'Czech Republic');
INSERT INTO country(id,name) VALUES (129,'Denmark');
INSERT INTO country(id,name) VALUES (130,'Estonia');
INSERT INTO country(id,name) VALUES (131,'Faroe Islands');
INSERT INTO country(id,name) VALUES (132,'Finland');
INSERT INTO country(id,name) VALUES (133,'France');
INSERT INTO country(id,name) VALUES (134,'Germany');
INSERT INTO country(id,name) VALUES (135,'Gibraltar');
INSERT INTO country(id,name) VALUES (136,'Greece');
INSERT INTO country(id,name) VALUES (137,'Greenland');
INSERT INTO country(id,name) VALUES (138,'Guernsey');
INSERT INTO country(id,name) VALUES (139,'Holy See (Vatican City State)');
INSERT INTO country(id,name) VALUES (140,'Hungary');
INSERT INTO country(id,name) VALUES (141,'Iceland');
INSERT INTO country(id,name) VALUES (142,'Ireland');
INSERT INTO country(id,name) VALUES (143,'Isle of Man');
INSERT INTO country(id,name) VALUES (144,'Italy');
INSERT INTO country(id,name) VALUES (145,'Jersey');
INSERT INTO country(id,name) VALUES (146,'Latvia');
INSERT INTO country(id,name) VALUES (147,'Liechtenstein');
INSERT INTO country(id,name) VALUES (148,'Lithuania');
INSERT INTO country(id,name) VALUES (149,'Luxembourg');
INSERT INTO country(id,name) VALUES (150,'Macedonia, the former Yugoslav Republic of');
INSERT INTO country(id,name) VALUES (151,'Malta');
INSERT INTO country(id,name) VALUES (152,'Monaco');
INSERT INTO country(id,name) VALUES (153,'Montenegro');
INSERT INTO country(id,name) VALUES (154,'Netherlands');
INSERT INTO country(id,name) VALUES (155,'Norway');
INSERT INTO country(id,name) VALUES (156,'Poland');
INSERT INTO country(id,name) VALUES (157,'Portugal');
INSERT INTO country(id,name) VALUES (158,'Romania');
INSERT INTO country(id,name) VALUES (159,'Serbia');
INSERT INTO country(id,name) VALUES (160,'Slovakia');
INSERT INTO country(id,name) VALUES (161,'Slovenia');
INSERT INTO country(id,name) VALUES (162,'Spain');
INSERT INTO country(id,name) VALUES (163,'Svalbard and Jan Mayen');
INSERT INTO country(id,name) VALUES (164,'Sweden');
INSERT INTO country(id,name) VALUES (165,'Switzerland');
INSERT INTO country(id,name) VALUES (166,'United Kingdom');
INSERT INTO country(id,name) VALUES (167,'Belize');
INSERT INTO country(id,name) VALUES (168,'Costa Rica');
INSERT INTO country(id,name) VALUES (169,'El Salvador');
INSERT INTO country(id,name) VALUES (170,'Guatemala');
INSERT INTO country(id,name) VALUES (171,'Honduras');
INSERT INTO country(id,name) VALUES (172,'Mexico');
INSERT INTO country(id,name) VALUES (173,'Nicaragua');
INSERT INTO country(id,name) VALUES (174,'Panama');
INSERT INTO country(id,name) VALUES (175,'Anguilla');
INSERT INTO country(id,name) VALUES (176,'Antigua and Barbuda');
INSERT INTO country(id,name) VALUES (177,'Aruba');
INSERT INTO country(id,name) VALUES (178,'Bahamas');
INSERT INTO country(id,name) VALUES (179,'Barbados');
INSERT INTO country(id,name) VALUES (180,'Bermuda');
INSERT INTO country(id,name) VALUES (181,'Bonaire, Sint Eustatius and Saba');
INSERT INTO country(id,name) VALUES (182,'Cayman Islands');
INSERT INTO country(id,name) VALUES (183,'Cuba');
INSERT INTO country(id,name) VALUES (184,'Curaao');
INSERT INTO country(id,name) VALUES (185,'Dominica');
INSERT INTO country(id,name) VALUES (186,'Dominican Republic');
INSERT INTO country(id,name) VALUES (187,'Grenada');
INSERT INTO country(id,name) VALUES (188,'Guadeloupe');
INSERT INTO country(id,name) VALUES (189,'Haiti');
INSERT INTO country(id,name) VALUES (190,'Jamaica');
INSERT INTO country(id,name) VALUES (191,'Martinique');
INSERT INTO country(id,name) VALUES (192,'Montserrat');
INSERT INTO country(id,name) VALUES (193,'Netherlands Antilles');
INSERT INTO country(id,name) VALUES (194,'Puerto Rico');
INSERT INTO country(id,name) VALUES (195,'Saint Barth_lemy');
INSERT INTO country(id,name) VALUES (196,'Saint Kitts and Nevis');
INSERT INTO country(id,name) VALUES (197,'Saint Lucia');
INSERT INTO country(id,name) VALUES (198,'Saint Martin (French part)');
INSERT INTO country(id,name) VALUES (199,'Saint Vincent and the Grenadines');
INSERT INTO country(id,name) VALUES (200,'Sint Maarten (Dutch part)');
INSERT INTO country(id,name) VALUES (201,'Trinidad and Tobago');
INSERT INTO country(id,name) VALUES (202,'Turks and Caicos Islands');
INSERT INTO country(id,name) VALUES (203,'Virgin Islands, British');
INSERT INTO country(id,name) VALUES (204,'Virgin Islands, U.S.');
INSERT INTO country(id,name) VALUES (205,'Canada');
INSERT INTO country(id,name) VALUES (206,'Saint Pierre and Miquelon');
INSERT INTO country(id,name) VALUES (207,'United States');
INSERT INTO country(id,name) VALUES (208,'Argentina');
INSERT INTO country(id,name) VALUES (209,'Bolivia, Plurinational States of');
INSERT INTO country(id,name) VALUES (210,'Brazil');
INSERT INTO country(id,name) VALUES (211,'Chile');
INSERT INTO country(id,name) VALUES (212,'Colombia');
INSERT INTO country(id,name) VALUES (213,'Ecuador');
INSERT INTO country(id,name) VALUES (214,'Falkland Islands (Malvinas)');
INSERT INTO country(id,name) VALUES (215,'French Guiana');
INSERT INTO country(id,name) VALUES (216,'Guyana');
INSERT INTO country(id,name) VALUES (217,'Paraguay');
INSERT INTO country(id,name) VALUES (218,'Peru');
INSERT INTO country(id,name) VALUES (219,'Suriname');
INSERT INTO country(id,name) VALUES (220,'Uruguay');
INSERT INTO country(id,name) VALUES (221,'Venezuela, Bolivarian Republic of');
INSERT INTO country(id,name) VALUES (222,'American Samoa');
INSERT INTO country(id,name) VALUES (223,'Australia');
INSERT INTO country(id,name) VALUES (224,'Christmas Island');
INSERT INTO country(id,name) VALUES (225,'Cocos (Keeling) Islands');
INSERT INTO country(id,name) VALUES (226,'Cook Islands');
INSERT INTO country(id,name) VALUES (227,'Fiji');
INSERT INTO country(id,name) VALUES (228,'French Polynesia');
INSERT INTO country(id,name) VALUES (229,'Guam');
INSERT INTO country(id,name) VALUES (230,'Kiribati');
INSERT INTO country(id,name) VALUES (231,'Marshall Islands');
INSERT INTO country(id,name) VALUES (232,'Micronesia, Federated States of');
INSERT INTO country(id,name) VALUES (233,'Nauru');
INSERT INTO country(id,name) VALUES (234,'New Caledonia');
INSERT INTO country(id,name) VALUES (235,'New Zealand');
INSERT INTO country(id,name) VALUES (236,'Niue');
INSERT INTO country(id,name) VALUES (237,'Norfolk Island');
INSERT INTO country(id,name) VALUES (238,'Northern Mariana Islands');
INSERT INTO country(id,name) VALUES (239,'Palau');
INSERT INTO country(id,name) VALUES (240,'Papua New Guinea');
INSERT INTO country(id,name) VALUES (241,'Pitcairn');
INSERT INTO country(id,name) VALUES (242,'Samoa');
INSERT INTO country(id,name) VALUES (243,'Solomon Islands');
INSERT INTO country(id,name) VALUES (244,'Tokelau');
INSERT INTO country(id,name) VALUES (245,'Tonga');
INSERT INTO country(id,name) VALUES (246,'Tuvalu');
INSERT INTO country(id,name) VALUES (247,'United States Minor Outlying Islands');
INSERT INTO country(id,name) VALUES (248,'Vanuatu');
INSERT INTO country(id,name) VALUES (249,'Wallis and Futuna');
